version: '3'

services:
  static:
    build: './static/'
    volumes:
      - ./static/html:/html

  api:
    build: './api/'
    command: 'adev runserver app.py --port 8080'
    volumes:
      - './api:/app'
    env_file: './api/.env'

  proxy:
    build: './proxy/'
    ports:
      - '8765:80'
    depends_on:
      - api
